### ISSUE TITLE
[전체] UI 및 버그 수정 

### ISSUE THREAD

**Issue by wody-d** [DeveloperAcademy-POSTECH/MC2-Team11-NDOM#80]
## TODO

~ 6.16 (목) 

#### 전체 
- [ ] 뒤로가기 버튼 터치영역 키우기 
- [ ] 로그인 뷰와 홈 뷰 연결 
- [ ] 로그인 뷰는 앱 처음 시작했을 때만 나오게 하기

#### 팝업 
- [ ] 나비 8글자 
- [ ] 고양이 이미지 추가 
- [ ] 합치기 화면 전환 
- [ ] 합치기 했을 때 완료화면 멘트 수정해서 분기처리해주기 

#### 홈 
- [ ] 더블 클릭했을 때, 줌아웃
- [ ] 팝업 끌 때, 줌아웃
- [ ] 사진 자르기 
- [ ] 고양이 배치 다시 
- [ ] 고양이 배치도를 13pro, mini

#### 기록 
- [ ] 왼쪽 위 x표시 
- [ ] 뒤로 가기 애니메이션 
- [ ] 네비게이션 바 색깔 주기 
- [ ] 나이 계산 로직 추가 (서버 연결 후)
- [ ] 개인 메모장 색깔 
- [ ] 건강상태 태그 주루룩 만들기
- [ ] 개인 메모장 스냅 기능 구현 

#### 급식 입력
- [ ] 급식 이름 크기 줄여서 10글자가 한줄에 나오게 (14글자)
- [ ] 수정 버튼과 급식 이름 간격 조금만 늘리기
- [ ] 시간 보낼 때 DateTime으로 보내는 로직 추가 (서버 연결 후)
- [ ] 마지막 사료 텍스트 추가 
- [ ] 급식 수정할 때 버튼을 회색으로 안 눌리게 (systemGray6)

#### 급수 입력 
- [ ] 급수 화면 연결 
- [ ] 급수 타이틀 바꾸기 
- [ ] 자정에 리셋 (서버 연결 후)

#### 건강상태 등록
- [ ] 8글자밖에 안 되는 것 수정하기 
- [ ] X버튼 양옆 패딩 주기
- [ ] 태그 남아있게 하기 (서버 연결 필수)
- [ ] 기본 태그는 무조건 지울 수 없게 하기 
- [ ] 기본 태그 뒤로가기 할 때 적용이 되버리는 이슈

#### 개인 메모장 등록
- [x] 문제없음 

#### 고양이 등록
- [ ] X 버튼 추가
- [ ] 다음 넘어가는 버튼 회색 처리하기 
- [ ] 나이 글자수 제한 두기
- [ ] 캐릭터 이미 등록된 건 제한 두기 (완전 후순위)
- [ ] 뒤로가기 제스쳐 (후순위)
- [ ] 완료하고 홈으로 갔을 때 이상한 애니메이션 수정 (후순위)
- [ ] 색깔 선택된 거 테두리 처리
- [ ] 완료페이지에서 뒤로가기 버튼 삭제하기
